import type { NextPage } from 'next';
import Head from 'next/head';
import Content from '../components/content';


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body>
        
        <Content></Content>

      </body>
    </>
  );
};

export default Home;
